import os
import autogen
import arxiv
from dotenv import load_dotenv

# --- TASK 1: Setup and API Keys ---
load_dotenv()
api_key = os.getenv("GROQ_API_KEY")

if api_key:
    print("API key loaded successfully!\n")
else:
    print("Error: API key not found. Check your .env file.\n")


# --- TASK 2: Implement arXiv Paper Search Function ---
def search_arxiv(query: str, max_results: int = 3) -> str:
    """
    Searches the arXiv database for academic papers based on a search query.
    Returns a formatted string containing the title, authors, link, and summary of the papers.
    """
    print(f"\n[Executing arXiv Search Tool] Searching for: '{query}'...\n")
    client = arxiv.Client()
    search = arxiv.Search(
        query=query,
        max_results=max_results,
        sort_by=arxiv.SortCriterion.Relevance
    )
    
    results = []
    for paper in client.results(search):
        paper_info = (
            f"Title: {paper.title}\n"
            # f"Authors: {', '.join([author.name for author in paper.authors])}\n"
            f"Link: {paper.entry_id}\n"
            f"Summary: {paper.summary}\n"
        )
        results.append(paper_info)

    if not results:
        return "No papers found for this query."
    return "\n----------------------------------------\n".join(results)


# --- TASKS 3 TO 7: Build the Agents ---
llm_config = {
    "config_list": [{
        "model": "llama-3.3-70b-versatile",
        "api_key": api_key,
        "base_url": "https://api.groq.com/openai/v1" 
    }],
    "temperature": 0.7, 
}

topic_agent = autogen.AssistantAgent(
    name="Topic_Refinement_Agent",
    system_message="""You are an expert academic researcher. 
    Your job is to take a broad research topic and refine it into 
    1-3 highly specific, relevant search queries that can be used to find academic papers. 
    CRITICAL: The arXiv search API crashes when given complex boolean logic. 
    You MUST NOT use 'AND', 'OR', quotation marks, or parentheses. 
    Provide only simple, plain-text keyword strings (e.g., large language models competitive programming code generation).""",
    llm_config=llm_config,
)
print("Task 3: Topic Refinement Agent initialized.")

discovery_agent = autogen.AssistantAgent(
    name="Paper_Discovery_Agent",
    system_message="""You are an expert Research Librarian. 
    Your job is to take the specific search queries provided by the Topic Refinement Agent 
    and use the `search_arxiv` tool to find relevant academic papers. 
    Once you receive the results from the tool, pass the raw paper data 
    (Title, Authors, Summary, Link) to the next agent for analysis. 
    IMPORTANT: Do not summarize the papers yourself. Only output the tool call.""",
    llm_config=llm_config,
)
print("Task 4: Paper Discovery Agent initialized.")

insight_agent = autogen.AssistantAgent(
    name="Insight_Synthesizer_Agent",
    system_message="""You are an expert AI Data Analyst. 
    Your job is to read the raw academic paper summaries provided to you by the Discovery Agent.
    You must extract the core methodologies, key findings, and main contributions of each paper. 
    Format these insights into a clear, structured bulleted list. Do not write a general summary; focus on the technical insights.""",
    llm_config=llm_config,
)
print("Task 5: Insight Synthesizer Agent initialized.")

report_agent = autogen.AssistantAgent(
    name="Report_Compiler_Agent",
    system_message="""You are an expert Technical Writer. 
    Your job is to take the structured bullet points from the Insight Synthesizer Agent 
    and compile them into a comprehensive, well-formatted markdown report. 
    The report should include a clear title, an introduction, a detailed breakdown of the papers, 
    and a brief concluding summary. Do not add any new external information; only use what was provided to you.""",
    llm_config=llm_config,
)
print("Task 6: Report Compiler Agent initialized.")

gap_agent = autogen.AssistantAgent(
    name="Gap_Analysis_Agent",
    system_message="""You are an expert Academic Strategist. 
    Your job is to critically evaluate the compiled markdown report generated by the Report Compiler Agent.
    Identify missing areas, limitations, or 'research gaps' in the current literature discussed. 
    Append a well-structured 'Future Research Directions' section to the end of the report 
    suggesting 2-3 novel areas for future study. When you have finished adding the Future Research Directions, you must output the exact word TERMINATE.""",
    llm_config=llm_config,
)
print("Task 7: Gap Analysis Agent initialized.")


# --- TASK 8: Define Termination Conditions ---
def is_termination_message(message: dict) -> bool:
    content = message.get("content", "")
    if content is None:
        return False
    return "TERMINATE" in content.upper()

print("Task 8: Termination condition defined.")


# --- TASK 9 & 10: Insert a User Proxy Agent and Register Tools ---
user_proxy = autogen.UserProxyAgent(
    name="Admin_User",
    system_message="You are the human supervisor. You will review the final report and decide if it is approved or needs revisions.",
    human_input_mode="ALWAYS", 
    code_execution_config={"use_docker": False} 
)
print("Task 10: User Proxy Agent initialized.")

# Bind the search_arxiv tool to the agents so they actually execute it
autogen.agentchat.register_function(
    search_arxiv,
    caller=discovery_agent,
    executor=user_proxy,
    name="search_arxiv",
    description="Searches the arXiv database for academic papers based on a search query."
)

# --- TASK 11: Implement Custom Selector and GroupChat ---
def state_transition(last_speaker, groupchat):
    """
    Traffic controller, updated to handle tool executions properly.
    """
    messages = groupchat.messages
    if not messages:
        return topic_agent
    
    last_message = messages[-1]
    
    # If the AI calls a tool, hand off to the user_proxy to execute it
    if "tool_calls" in last_message or "function_call" in last_message:
        return user_proxy
        
    # If the user_proxy just finished running the tool, pass the real arXiv results to the insight agent
    if last_speaker is user_proxy and last_message.get("role") == "tool":
        return insight_agent
        
    # Standard sequential assembly line
    if last_speaker is topic_agent:
        return discovery_agent
    if last_speaker is discovery_agent:
        return insight_agent
    if last_speaker is insight_agent:
        return report_agent
    if last_speaker is report_agent:
        return gap_agent
        
    # Hand off to the human at the very end
    if last_speaker is gap_agent:
        return user_proxy
        
    # Human approval logic
    if last_speaker is user_proxy:
        if "APPROVE" in last_message.get("content", "").upper():
            return None  # Ends the chat
        else:
            return topic_agent # Restarts the search based on feedback

# GroupChat logic
groupchat = autogen.GroupChat(
    agents=[user_proxy, topic_agent, discovery_agent, insight_agent, report_agent, gap_agent],
    messages=[],
    max_round=20
)

groupchat.speaker_selection_method = state_transition

manager = autogen.GroupChatManager(
    groupchat=groupchat,
    llm_config=llm_config,
    is_termination_msg=is_termination_message
)
print("Task 11: Custom Selector Function defined and Workflow updated.\n")


# --- TASK 12: Execute the Full Interactive Research Workflow ---
if __name__ == "__main__":
    print("Task 12: Starting the research workflow...\n")
    
    # Ask the user for the topic dynamically
    research_topic = input("\nWhat topic would you like the AI team to research today? \n> ")
    
    # Kick off the chat
    user_proxy.initiate_chat(
        manager,
        message=f"Please research the following topic: {research_topic}"
    )

    # Save the final report to a Markdown file
    safe_filename = "".join(c if c.isalnum() else "_" for c in research_topic)[:30] + "_report.md"
    
    with open(safe_filename, "w", encoding="utf-8") as f:
        for msg in groupchat.messages:
            agent_name = msg.get("name", "")
            content = msg.get("content", "")
            
            # Only save the text generated by the Report and Gap agents
            if agent_name in ["Report_Compiler_Agent", "Gap_Analysis_Agent"] and content:
                # Remove the 'TERMINATE' command so it doesn't show up in the final document
                clean_content = content.replace("TERMINATE", "").strip()
                f.write(clean_content + "\n\n")
                
    print(f"\n[+] Success! The final research report has been saved to your project folder as: {safe_filename}")